language: c

os:
  - linux
  - osx

dist: trusty
sudo: false

# OS X only supports one image. Use the latest.
osx_image: xcode8.2

git:
  depth: 2

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7

env:
  global:
    - BUILD_JOBS=2

  matrix:
    - BUILD_SOURCE=clmul-x86.c
    - BUILD_SOURCE=sha1-x86.c
    - BUILD_SOURCE=sha256-x86.c

    # Travis cannot do native ARM
    # - BUILD_SOURCE=clmul-arm.c
    # - BUILD_SOURCE=sha1-arm.c
    # - BUILD_SOURCE=sha256-arm.c

matrix:
  exclude:
    - os: osx
      compiler: gcc

# Whitelist branches to avoid testing branches
branches:
  only:
    - master

before_install:
  - if [ $CC == gcc ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CC=gcc-7; fi
   
script:
  - $CC -Wall cpuid.c -o cpuid-sha.exe && ./cpuid-sha.exe
  - $CC -Wall -DTEST_MAIN=1 -mpclmul -msha -msse4 $BUILD_SOURCE -o test.exe && ./test.exe

#notifications:
#  email: jdoe@example.com
