language: c

os:
  - linux
  - osx

dist: trusty
sudo: true

# OS X only supports one image. Use the latest.
osx_image: xcode8.3

git:
  depth: 2

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7

env:
  global:
    - BUILD_JOBS=2

  matrix:
    - BUILD_SOURCE=sha1-x86.c
    - BUILD_SOURCE=sha256-x86.c

    # Travis cannot do native ARM
    # - BUILD_SOURCE=sha1-arm.c
    # - BUILD_SOURCE=sha256-arm.c

matrix:
  exclude:
    - os: osx
      compiler: gcc

# Whitelist branches to avoid testing branches
branches:
  only:
    - master

before_install:
  - if [ $CC == gcc ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CC=gcc-7; fi
  - export SDE_BIN=sde
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ `uname -m` = x86_64 ]; then export SDE_BIN=sde64; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo sysctl kernel.yama.ptrace_scope=0; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget -q ${SDE_URL}; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xvf ${SDE_ARCHIVE}.tar.bz2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=${PATH}:${TRAVIS_BUILD_DIR}/${SDE_ARCHIVE}; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget -q ${SDE_OSX_URL}; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar xvf ${SDE_OSX_ARCHIVE}.tar.bz2; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=${PATH}:${TRAVIS_BUILD_DIR}/${SDE_OSX_ARCHIVE}; fi

script:
  - $CC -Wall cpuid.c -o cpuid-sha.exe
  - $CC -Wall -DTEST_MAIN=1 -msha -msse4 $BUILD_SOURCE -o test.exe
  - if ./cpuid-sha.exe -q; then ./test.exe; else $SDE_BIN -- ./test.exe; fi

#notifications:
#  email: jdoe@example.com
